[project]
name = "swapi-client"
authors = ["Adrian Ciolek <ciolek.adrian@protonmail.com>"]
version = "0.0.1"
description = "A unofficial Python client for the SerwisPlanner API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.20.0",
]
